### ISSUE TITLE
GitHub Actionsの修正

### ISSUE THREAD

**Issue by shouta0715** [ogurilab/school-lunch-api#9]
```yml
uses: actions/setup-go@v4
        with:
          go-version-file: app/go.mod
          cache: true
          cache-dependency-path: app/go.sum

```

に修正する必要がある。
